apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-configs-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboards-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-provisioning-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-config-pvc
  namespace: porto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
