FROM python:3.12

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir streamlit requests plotly

COPY . .

ENV PYTHONPATH=/app

EXPOSE 8501
CMD ["streamlit", "run", "src/inference/client.py", "--server.address=0.0.0.0", "--server.port=8501"]
